# Generated by Django 4.0.1 on 2022-03-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oder_id', models.SlugField()),
                ('product', models.ManyToManyField(related_name='produc', to='payment.Product')),
            ],
        ),
    ]
