# Generated by Django 4.0.1 on 2022-03-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.SlugField(max_length=16)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.job')),
            ],
        ),
    ]
