# Generated by Django 4.0.1 on 2022-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_programmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmers',
            name='is_true',
            field=models.BooleanField(default=True),
        ),
    ]
