# Generated by Django 4.0.1 on 2022-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
