# Generated by Django 4.0.1 on 2022-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_programmers_is_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='programmers',
            name='languages',
            field=models.ManyToManyField(to='example.Language'),
        ),
    ]
