# Generated by Django 4.0.1 on 2022-03-19 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='key',
        ),
        migrations.RemoveField(
            model_name='programmers',
            name='company',
        ),
        migrations.RemoveField(
            model_name='programmers',
            name='languages',
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Programmers',
        ),
    ]
